name: CI devops 2022
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: [ origin, main ]
  pull_request:

jobs:
  # Use the docker.yml file and the backend_test.yml file to do the CI/CD
  back_end_tests:
    uses: ./.github/workflows/backend_test.yml
    with:
      project_key: 'JiaenLiu123_simple-api-student'
      organization: 'jiaenliu123'
      pom_path: './pom.xml'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  build_and_push_docker_image:
    uses: ./.github/workflows/docker.yml
    with:
      back_end_path: '.'
      database_path: './postgresql'
      httpd_server_path: './http_server'
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
